apiVersion: v1
kind: Service
metadata:
  name: platform-backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: platform-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http


