apiVersion: v1
kind: Service
metadata:
  name: platform-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: platform-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http


