apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.backend.secret.DJANGO_SECRET_KEY | quote }}
  DJANGO_API_KEY: {{ .Values.backend.secret.DJANGO_API_KEY | quote }}
  SENTRY_DSN: {{ .Values.backend.secret.SENTRY_DSN | quote }}
  DATABASE_URL: {{ .Values.backend.secret.DATABASE_URL | default "" | quote }}


