version: '3.8'

services:
  neo4j:
    image: neo4j:5.15.0
    container_name: quantia_graph
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/quantia_secret_password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
